filebeat.inputs:

- type: log
  enabled: true

  paths:
    - /var/log/*.log

output.elasticsearch:
  hosts: ["http://es01:9200"]
  username: elastic
  password: "你的Elastic密碼"

setup.kibana:
  host: "kibana:5601"
